### ISSUE TITLE
ImportError: cannot import name 'core_rnn_cell_impl'怎么处理呢？

### ISSUE THREAD

**Issue by ghost** [indiejoseph/doc-han-att#6]
Traceback (most recent call last):
  File "train.py", line 7, in <module>
    from model import Model
  File "/software/home/zhongsl/han005/model.py", line 6, in <module>
    from ran_cell import RANCell
  File "/software/home/zhongsl/han005/ran_cell.py", line 10, in <module>
    from tensorflow.contrib.rnn.python.ops import core_rnn_cell_impl
ImportError: cannot import name 'core_rnn_cell_impl'
谢谢！Thanks！

**Comment by YFwang1992** [comment]
you can use tf 1.1 ，some path change after 1.2 ,hope can help you
